CREATE TABLE IF NOT EXISTS barang (
	kode VARCHAR(255) PRIMARY KEY,
	nama VARCHAR(255) NOT NULL,
	harga INT(255) NOT NULL,
	jumlah INT(255) NOT NULL,
	kode_spl VARCHAR(255) NOT NULL
	
);

CREATE TABLE IF NOT EXISTS supplier (
	kode_spl VARCHAR(255) PRIMARY KEY,
	nama VARCHAR(255) NOT NULL,
	alamat VARCHAR(255) NOT NULL,
	kota VARCHAR(255) NOT NULL,
	telpon INT(255) NOT NULL

);